spring:
    application:
        name: ${APPLICATION_NAME:payment-service}
server:
    port: ${SERVER_PORT:8081}
eureka:
    client:
        register-with-eureka: ${REGISTER_WITH_EUREKA:true}
        service-url.defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka}